version: '3.8'
services:
  solid-app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: vite_docker_image
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:delegated"
      - /usr/src/app/node_modules
    
