# docker-compose.yml

version: '3.8'
services:
  vite-application:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app:delegated"
      - /usr/src/app/node_modules
    
